---
- hosts: all
  become: true
  tasks:
    - name: Copy war onto tomcat server
      copy:
            src: /ansibledemo/warfile/dynamic_new-17.war

            dest: /apache-tomcat-9.0.37/webapps
...